DROP TABLE IF EXISTS CompletedExerciseCalendarTable;
DROP TABLE IF EXISTS CompletedExerciseTable;
DROP TABLE IF EXISTS ScheduleTable;
DROP TABLE IF EXISTS MLConfigTable;
DROP TABLE IF EXISTS ExerciseTable;
DROP TABLE IF EXISTS UserTable;
CREATE TABLE MLConfigTable ( id INTEGER PRIMARY KEY NOT NULL, coordinates  TEXT NOT NULL );
CREATE TABLE ExerciseTable ( id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL, mlId INTEGER NOT NULL, FOREIGN KEY ( mlId ) REFERENCES MLConfigTable (id) ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE UserTable ( id INTEGER PRIMARY KEY NOT NULL, userName TEXT NOT NULL, password TEXT NOT NULL, height FLOAT  NOT NULL, weight FLOAT  NOT NULL, bmi FLOAT  NOT NULL);
CREATE TABLE ScheduleTable ( id INTEGER PRIMARY KEY NOT NULL,user_id INTEGER NOT NULL, exercise_id INTEGER NOT NULL, startDateTime TEXT NOT NULL, notes TEXT NULL ,no_of_sets INTEGER NOT NULL, title TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES UserTable (id),FOREIGN KEY (exercise_id) REFERENCES ExerciseTable (id));
CREATE TABLE CompletedExerciseTable ( user_id INTEGER NOT NULL, exercise_id INTEGER NOT NULL, completed_dateTime TEXT NOT NULL, total_calories FLOAT NOT NULL, no_completed_sets INTEGER DEFAULT 0, PRIMARY KEY(user_id,exercise_id,completed_dateTime), FOREIGN KEY (user_id) REFERENCES UserTable (id),FOREIGN KEY (exercise_id) REFERENCES ExerciseTable (id));
CREATE TABLE CompletedExerciseCalendarTable ( schedule_id INTEGER NOT NULL, user_id INTEGER NOT NULL, exercise_id INTEGER NOT NULL, completed_dateTime TEXT NOT NULL, isCompleted INTEGER NOT NULL, PRIMARY KEY(schedule_id,user_id,exercise_id,completed_dateTime), FOREIGN KEY (user_id,exercise_id,completed_dateTime) REFERENCES CompletedExerciseTable (user_id,exercise_id,completed_dateTime),FOREIGN KEY (schedule_id) REFERENCES ScheduleTable(id) );
INSERT INTO UserTable (userName,password,height,weight,bmi) VALUES( "Sam", "password",163.5, 75.3,13.3);
INSERT INTO UserTable (userName,password,height,weight,bmi) VALUES( "Jane", "password",183.5, 75.3,13.3);
INSERT INTO UserTable (userName,password,height,weight,bmi) VALUES( "kasy", "password",193.5, 75.3,13.3);
INSERT INTO MLConfigTable (coordinates) VALUES("12.3 , 11.1, 11.1");
INSERT INTO MLConfigTable (coordinates) VALUES("12.3 , 11.1, 11.1");
INSERT INTO MLConfigTable (coordinates) VALUES("12.3 , 11.1, 11.1");
INSERT INTO MLConfigTable (coordinates) VALUES("12.3 , 11.1, 11.1");
INSERT INTO ExerciseTable (name, mlId) VALUES("pushups",1);
INSERT INTO ExerciseTable (name, mlId) VALUES("squats",2);
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,1,"2022-03-23 00:00:00.000","Must do workout!",4,"abs");
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,2,"2022-03-23 00:00:00.000","Must run",3,"legs");
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,2,"2022-03-24 00:00:00.000","Must do workout!",2,"arms");
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,1,"2022-03-25 00:00:00.000","Must do workout!",8,"abs");
INSERT INTO CompletedExerciseTable (user_id, exercise_id,completed_dateTime,total_calories,no_completed_sets) VALUES(1,1,"2022-03-23 00:00:00.000",112,4);
INSERT INTO CompletedExerciseTable (user_id, exercise_id,completed_dateTime,total_calories,no_completed_sets) VALUES(1,1,"2022-03-25 00:00:00.000",100,3);
INSERT INTO CompletedExerciseTable (user_id, exercise_id,completed_dateTime,total_calories,no_completed_sets) VALUES(1,2,"2022-03-23 00:00:00.000",132,4);
INSERT INTO CompletedExerciseCalendarTable(schedule_id,user_id,exercise_id,completed_dateTime,isCompleted) VALUES (1,1,1,"2022-03-23 00:00:00.000",1);
INSERT INTO CompletedExerciseCalendarTable(schedule_id,user_id,exercise_id,completed_dateTime,isCompleted) VALUES (2,1,2,"2022-03-23 00:00:00.000",1);