DROP TABLE IF EXISTS CompletedExerciseTable;
DROP TABLE IF EXISTS ScheduleTable;
DROP TABLE IF EXISTS ExerciseTable;
DROP TABLE IF EXISTS UserTable;
CREATE TABLE ExerciseTable ( id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL);
CREATE TABLE UserTable ( id INTEGER PRIMARY KEY NOT NULL, userName TEXT NOT NULL, password TEXT NOT NULL, height FLOAT  NOT NULL, weight FLOAT  NOT NULL, bmi FLOAT  NOT NULL);
CREATE TABLE ScheduleTable ( id INTEGER PRIMARY KEY NOT NULL,user_id INTEGER NOT NULL, exercise_id INTEGER NOT NULL, startDateTime TEXT NOT NULL, notes TEXT NULL ,no_of_sets INTEGER NOT NULL, title TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES UserTable (id),FOREIGN KEY (exercise_id) REFERENCES ExerciseTable (id));
CREATE TABLE CompletedExerciseTable ( user_id INTEGER NOT NULL, exercise_id INTEGER NOT NULL, completed_dateTime TEXT NOT NULL, total_calories FLOAT NOT NULL, no_completed_sets INTEGER DEFAULT 0, PRIMARY KEY(user_id,exercise_id,completed_dateTime), FOREIGN KEY (user_id) REFERENCES UserTable (id),FOREIGN KEY (exercise_id) REFERENCES ExerciseTable (id));
INSERT INTO UserTable (userName,password,height,weight,bmi) VALUES( "Sam", "password",163.5, 75.3,13.3);
INSERT INTO UserTable (userName,password,height,weight,bmi) VALUES( "Jane", "password",183.5, 75.3,13.3);
INSERT INTO UserTable (userName,password,height,weight,bmi) VALUES( "kasy", "password",193.5, 75.3,13.3);
INSERT INTO ExerciseTable (name) VALUES("pushups");
INSERT INTO ExerciseTable (name) VALUES("squats");
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,1,"2022-03-23 00:00","Must complete today's workout",4,"Exercise Day 1");
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,2,"2022-03-23 00:00","For weight cutting",3,"Exercise Day 2");
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,2,"2022-03-24 00:00","Gain Muscles!",2,"Exercise Day 3");
INSERT INTO ScheduleTable (user_id, exercise_id,startDateTime,notes,no_of_sets,title) VALUES(1,1,"2022-03-25 00:00","For Health",8,"Exercise Day 4");
INSERT INTO CompletedExerciseTable (user_id, exercise_id,completed_dateTime,total_calories,no_completed_sets) VALUES(1,1,"2022-03-23 00:00",112,4);
INSERT INTO CompletedExerciseTable (user_id, exercise_id,completed_dateTime,total_calories,no_completed_sets) VALUES(1,1,"2022-03-25 00:00",100,3);
INSERT INTO CompletedExerciseTable (user_id, exercise_id,completed_dateTime,total_calories,no_completed_sets) VALUES(1,2,"2022-03-23 00:00",132,4);
